### ISSUE TITLE
required ... is not required ? 

### ISSUE THREAD

**Issue by LasneF** [Gi60s/openapi-enforcer#137]
given the definition there about required statement of json schema 

https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.4.3.2 
ie 
[5.4.3](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.4.3).  required

[5.4.3.1](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.4.3.1).  Valid values

   The value of this keyword MUST be an array.  This array MUST have at
   least one element.  Elements of this array MUST be strings, and MUST
   be unique.

[5.4.3.2](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.4.3.2).  Conditions for successful validation

   An object instance is valid against this keyword if its property set
   contains all elements in this keyword's array value.

given this object 
```
  MyData:
    type: object
    required:
      - "a"
      - "b"
    properties:
      a:
        type: string
        description: field a
      c:
        type: string
        description: field c  
```

this object pass the enforcer validation dispite the fact that the object has no b field , 

what about raising a warning if not even an error ?
