### ISSUE TITLE
WSCH006: Detects issues where no issue exists

### ISSUE THREAD

**Issue by sonnypersch** [Gi60s/openapi-enforcer#142]
Hi,

Assume the following attribute definition:

```yaml
birthDate:
  type: string
  pattern: ^([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))$
  example: 1980-09-22
  description: Birth date of customer
```

The validator reports an example problem:
```
at: birthDate > example
  Example not valid. [WSCH006]
    Unable to deserialize value
      Expected a string. Received: 1980-09-22T00:00:00.000Z
```

The received value is unequal to the example value. It seems like the script parses the field as a date incl. timestamp.
