### ISSUE TITLE
Empty strings not allowed

### ISSUE THREAD

**Issue by erezarnon** [Gi60s/openapi-enforcer#154]
In API `parameters` definition (Notice there is not `minLength` or `pattern`):

```
- name: q
        in: query
        schema:
          type: string
```

Call `enforcer.request({query: {q: ''}})` and receive the following error

```
Request has one or more errors
  In query parameters
    at: q
      Unable to parse value
        Empty value not allowed
```

**Expected behavior:** An empty string should be accepted
