### ISSUE TITLE
Cannot validate arrays in the query string when using openapi.request

### ISSUE THREAD

**Issue by drewpureescapes** [Gi60s/openapi-enforcer#156]
When using the openapi.request function (https://openapi-enforcer.com/api/components/openapi.html#request) having query string parameters that are an array of enums like:
```
    arrayenums:
      name: arrayenums
      in: query
      description: 0-n from the enum list
      required: false
      schema:
        type: array
        items:
          type: string
          enum:
            - "Foo"
            - "Bar"
            - "Baz"
```

and calling the function like: 

```
const input = {
    method: 'GET',
    path: '/foo',
    query: {
        arrayenums: ['Foo', 'Bar'],
    },
};
const [req, validationError] = openapi.request(input);
```

I get the error `Expected an object with string keys and string values`.

I've tried comma separating the item to be like 'Foo,Bar' but then it fails the enum check. 

Is it not possible to validate an item from the query string that's an array?
